spring:
  application:
    name: fintracking-transaction
  datasource:
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        format_sql: true
    show-sql: false

server:
  port: 0
